### ISSUE TITLE
module 'pixray' has no attribute 'reset_settings'

### ISSUE THREAD

**Issue by mohamedabidi97** [dribnet/pixray#12]
Hi there,
( An error in the Start demo )
After running the first cell and restart the runtime. I had this error in the second one : 

AttributeError: module 'pixray' has no attribute 'add_settings'

**Comment by noble-born** [comment]
> Hi there, ( An error in the Start demo ) After running the first cell and restart the runtime. I had this error in the second one :
> 
> AttributeError: module 'pixray' has no attribute 'add_settings'

Hi! I got the same. What was the solution for you?
