### ISSUE TITLE
keyerror for 'pixel' on PixelDraw notebook

### ISSUE THREAD

**Issue by Esshahn** [dribnet/pixray#38]
I can't start the PixelDraw notebook with the drawer set to 'pixel'.
It gives a key error.
Any idea on how to fix this?

<img width="849" alt="Bildschirmfoto 2021-11-19 um 16 47 23" src="https://user-images.githubusercontent.com/434355/142651218-bb85dc7d-7451-4fbf-969c-2f236f032a43.png">
.

**Comment by Esshahn** [comment]
Just found this issue in the closed issues section. Restarting the runtime as advised worked.

**Comment by sungkhum** [comment]
I get this issue even with restarting the runtime...Any ideas how to fix it?
