### ISSUE TITLE
Docker installation error: failed to solve: executor failed running

### ISSUE THREAD

**Issue by Esshahn** [dribnet/pixray#39]
Installation via Docker is stuck with the following error:

```
error: failed to solve: executor failed running [/bin/sh -c pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt]: exit code: 137
ⅹ Failed to build Docker image: exit status 1
```

I think this is not related to pixray, but maybe you have an idea what's going wrong?
Thank you very much

**Comment by dribnet** [comment]
Sorry - yes this is a docker issue. You can skip docker and simply install requirements.txt in a separate environment instead as a workaround.
