### ISSUE TITLE
Pixray missing pixray.reset_settings() in Pixray PixelDraw demo colab

### ISSUE THREAD

**Issue by LulzRose** [dribnet/pixray#4]
When trying to run the pixray pixel draw demo I am receiving this error? Is their a fix?

`AttributeError                            Traceback (most recent call last)

<ipython-input-3-87cf0e7b99bf> in <module>()
     30 
     31 # these are good settings for pixeldraw
---> 32 pixray.reset_settings()
     33 pixray.add_settings(prompts=prompts, aspect=aspect)
     34 pixray.add_settings(quality="better", scale=2.5)

AttributeError: module 'pixray' has no attribute 'reset_settings'`

**Comment by dribnet** [comment]
Try restarting the co-lab and running all cells again (using the co-lab menus). In my experience this error is the result of not restarting the co-lab after the first setup cell is run.

**Comment by dribnet** [comment]
closing but feel free to reopen if this happens outside of the setup cell not being rerun
