### ISSUE TITLE
Pixray pixel notebook generates black images

### ISSUE THREAD

**Issue by Esshahn** [dribnet/pixray#40]
<img width="710" alt="Bildschirmfoto 2021-11-20 um 11 35 46" src="https://user-images.githubusercontent.com/434355/142723221-b8a0b7f2-c567-411e-91df-46d3214877dc.png">

I'm running this as described in the notebook. Mac, Chrome.
(btw on Safari the notebook gives an error as the audio output is permission restricted on the browser)

**Comment by dribnet** [comment]
The warning means that you didn't get a GPU capable of running in pixel mode. You can:

 1) Use drawer=vqgan isntead
 2) Upgrade to colab pro, or
 3) Use the free gob [text2pixel pixray interface](https://pixray.gob.io/text2pixel/) instead
