### ISSUE TITLE
Pixel

### ISSUE THREAD

**Issue by hai8023** [dribnet/pixray#6]
Where can I set the size of each cell in a pixel image? I searched for a long time but didn't find it.

**Comment by dribnet** [comment]
The simplest is to use `pixel_scale`

```python
pixray.add_settings(pixel_scale=2)
```
![scale_2](https://user-images.githubusercontent.com/945979/134275098-2a67f036-35d0-4b4a-9208-a096dde1e4d1.png)

```python
pixray.add_settings(pixel_scale=0.75)
```
![scale_75](https://user-images.githubusercontent.com/945979/134275140-1e073a33-42d9-4f76-97a9-2e5aa8080589.png)

**Comment by hai8023** [comment]
Okay, I understand, thank you for your quick reply
